steps:
  - name: gradle:7.1.1-jdk8
    entrypoint: gradle
    args: ["assemble"]
  - id: 'pull image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [
        '-c',
        'docker pull gcr.io/$PROJECT_ID/contactservice:latest || exit 0'
    ]
  - name: gcr.io/cloud-builders/docker
    args: [ "build",
            "-t",
            "gcr.io/$PROJECT_ID/contactservice:$COMMIT_SHA",
            '-t',
            'gcr.io/$PROJECT_ID/contactservice:latest',
            "." ]
  - id: 'deploy'
    name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'apply', '-f', 'k8s/' ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=rajutechies-cluster'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
        'set',
        'image',
        'deployment',
        'contactservice',
        'contactservice=gcr.io/$PROJECT_ID/contactservice:$COMMIT_SHA'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=rajutechies-cluster'
tags: ['master']
images: ["gcr.io/$PROJECT_ID/contactservice:$COMMIT_SHA",
          'gcr.io/$PROJECT_ID/contactservice:latest']
